### ISSUE TITLE
🙋 ID-request

### ISSUE THREAD

**Issue by schumannj** [nfdi4cat/voc4cat#36]
### Your ORCID identifier.

0000-0002-4041-0165

### The ROR of the organization you work for.

https://ror.org/01hcx6992

### Number of IDs requested.

100

### Additional information.

I want to extend the vocabulary with central concepts from thermal, heterogeneous catalysis that I will also be using in NOMAD.

**Comment by dalito** [comment]
Welcome Julia! #37 reserved IDS 7001...7100 for you. Please don't hesitate to create bug reports if you spot strange points. We are very interested in feedback from new people.

@nmoust from LIKAT has quite a big list of terms in the pipeline. You may talk to him whether it makes sense to coordinate work. However, if you just want to add some terms quickly, just go ahead!
