### ISSUE TITLE
💡 Better definition of selectivity

### ISSUE THREAD

**Issue by dalito** [nfdi4cat/voc4cat#46]
### Description

Brought up in #45

**Comment by schumannj** [comment]
The currently existing definition for selectivity is not general enough and does not capture what we need to annotate data in existing datasets: "In photocatalytic processes where product formation is expected, selectivity describes the ability of a photocatalyst to produce only the desired product with minimal (or none) of byproducts." 

The definition I suggest "A property of a product that refers to the ratio of products obtained from given reactants in a chemical reaction." is more data focused. The definitions could be extended by the formula "S(product)=Amount of product/ Sum over all products" and include the ambiguity that sometimes products are assigned special weight factors depending on the number of reactant molecule that goes into each product.

**Comment by dalito** [comment]
Selectivity is a complex beast to define (also IUPAC [GoldBook](https://doi.org/10.1351/goldbook.S05563) is not so great).

In my opinion selectivity is not related to the catalyst itself but is a general concept relevant for chemical reaction networks. So it could be defined as "Selectivity quantifies the ratio of a specific reactions product to a set of reaction products."

The are various sub-concepts:
- mass-based selectivity
- element-based selectivity (which is most popular in homogeneous and heterogeneous catalysis and in most often C-based)
- custom selectivities
  - which refer to special calculation variants
  - which refer to only a part of the products (e.g. only to observed gas-phase products ignoring coke)

**Comment by RoteKekse** [comment]
Hey all, 
Is selectivity not always a ratio between the increase of a product with the decrease of one or more reactants? 
How you quantify increase and decrease may vary mass, element counts, or others, but is not touched by this?

best Micha

**Comment by dalito** [comment]
The increase/decrease happens in a reaction network. So the definitions are very similar. Defining selectivity purely based on products has been quite common in projects I worked on which is why I avoided adding the term "reactants" to the definition explicitly.

**Comment by RoteKekse** [comment]
How do you define selectivity solely based on products?

**Comment by dalito** [comment]
E.g. for the reaction network
```
CO2 + H2 --> CO + H2O
CO2 + H2 --> CH4 + 2 H2O
```
the selectivity to to CO is `S(CO) = mol(CO) / (mol(CO) + mol(CH4))`
```

**Comment by schumannj** [comment]
it is the fraction of one product over the sum of all products, which should ideally be the same as the decrease of reactants. This is why you can also define 2 conversions - reactant based and product based. For small conversion the error is typically higher in determining a small change in a large amount of reactant, whereas the determination of a small amount of products has a smaller absolute error.

**Comment by dalito** [comment]
Yes, I also missed "network". My issues with this def is that it is longer but not more precise: Is the selectivity "described by a ratio" or would "is a ratio" be better? Do you mean "physical quality" in the sense of [PATO](https://ontobee.org/ontology/PATO?iri=http://purl.obolibrary.org/obo/PATO_0001018)? [qudt](https://qudt.org/) uses the term "quantity kind". However, the term selectivity is neither a quantity kind nor a (PATO-)"physical quality" since it subsumes different selectivity quantity kinds.

Mixing your addition of an "amount" into the short def would give my current favorite: `Selectivity quantifies the ratio between the amount of a specific reaction product and the amount of a set of reaction products in a reaction network.` and add (maybe) `The amount can be quantified in different way, e.g. by mass or mole, giving different kinds of selectivity.`

**Comment by RoteKekse** [comment]
Hey David, yes I used physical quality from PATO usually as a subclass of quality from BFO as it is done in the CHMO. 

2 things. I think it is important to leave it open if the ratio is with respect to products or reactants. We can have more specific selectivities with a clear calculation rule additionally. 

As a non chemist I am still struggling with the semantic difference of a chemical reaction and a chemical reaction network. Either the latter is a model for the former or it seems to be the same thing.

**Comment by dalito** [comment]
To get around reaction vs. reaction network we could just use `chemical conversion`. Here is a new proposal that avoids the problem of reactant / product distinction:

Selectivity: `A dimensionless physical quantity describing how effective a reactant is converted to the desired product in a chemical conversion. It is calculated as the ratio between the amount of the desired product and the amount of the desired product that could have been formed if all reactants were converted to the desired product. The selectivity is 1 (or 100 %) if no other than the desired product is formed.`

**Comment by schumannj** [comment]
I like the new definition for selectivity. should it replace the old definition or is it a new concept? I could add it in my next PR

**Comment by dalito** [comment]
I will add it along with yield and conversion.

**Comment by dalito** [comment]
@schumannj see #58

Thank you all for the discussion here!
