### ISSUE TITLE
Access Rights Pushing To branch

### ISSUE THREAD

**Issue by RoteKekse** [nfdi4cat/voc4cat#54]
Hello NFDI4Cat,

Can someone grant me rights to push to branches which are none main :)? @dalito ?

Best
Micha

**Comment by dalito** [comment]
The contribution process is via forking. So you should fork this repo (github.com/rotekekse/voc4cat), create a feature branch in your fork (rotekekse/voc4cat/myfeature), push updates to your feature branch and then submit a PR from your feature branch to voc4cat/main. 

Do yourself a favor and do never commit to the main branch of your fork but always to the new feature branch. If you commit to main you have to handle conflicts between your fork´s main branch and main branch of voc4cat.

**Comment by RoteKekse** [comment]
Ah yes makes sense thanks.
