### ISSUE TITLE
🙋 ID-request

### ISSUE THREAD

**Issue by khatamirad** [nfdi4cat/voc4cat#79]
### Your ORCID identifier.

0000-0002-6723-1650

### The ROR of the organization you work for.

https://ror.org/03v4gjf40

### Number of IDs requested.

20

**Comment by dalito** [comment]
Do you really want just one single ID? Typically we reserve a range of 10 or more so that you don't have to ask again for the next contribution.

**Comment by dalito** [comment]
FYI: If the text of an existing comment is edited, I don't get a notified. Obviously GitHub sends notification only for new comments. So I was not aware that you changed the number of IDs in the request.
