### ISSUE TITLE
📝 Provide guidelines also as searchable documentation

### ISSUE THREAD

**Issue by dalito** [nfdi4cat/voc4cat#91]
### Observed in version

2.0

### Description

The guidelines should be more easily accessible. We should also publish them as web-based documentation (not just as pdf on Zenodo). 

ToDos:

- [x] Convert guidelines to markdown with [pandoc](https://pandoc.org/)
- [x] Setup [sphinx](https://www.sphinx-doc.org/) as documentation generator including [MyST](https://myst-parser.readthedocs.io/) for markdown support
- [x] Add documentation generation to gh-actions. We must be careful not to interfere with the current use of gh-pages for publishing the vocabulary´s SKOS-files and html-pages for each version of the vocabulary.

**Comment by nmoust** [comment]
Created the Voc4Cat logo in .svg: 

![voc4cat logo](https://github.com/user-attachments/assets/bb07d8db-6749-4aeb-86ac-504f5b288d7f)

**Comment by dalito** [comment]
@nmoust Thanks for making the svg file! I derived two variants from it for dark and light themes. 

While doing so I noticed that the C in **Cat** has a different color than **at**. For the final logo-files, I changed the svg-code to use the same blue for all three letters.
