### ISSUE TITLE
Updated version of .svg logo for Voc4Cat (HTML documentation)

### ISSUE THREAD

**Issue by nmoust** [nfdi4cat/voc4cat#98]
Dear Dr. Linke,

I slightly changed the Voc4Cat logo to be used as an .svg in the HTML documentation.

The changes include:
- Increased the size of the"Voc"
- Brought "V", "o", and "c" closer together.
- Now "C", "a", and "t" have the same colour (005C93).
- The .svg now is exported in a way that there is no "empty" space surrounding the actual logo.

![Updated voc4cat logo](https://github.com/user-attachments/assets/c28d8928-a59a-478b-90bc-0770280d035e)

**Comment by dalito** [comment]
Thanks. This looks clearly better from spacing then the one in #91.

**Comment by dalito** [comment]
The merged svg icon that is now shown on the site has the improved spacing, corrected colors and no extra padding around it.

@nmoust - What do you think about the small images on the new [welcome page](https://nfdi4cat.github.io/voc4cat/)?

I do no longer like the xlsx-icon overlay in the middle (although I made it). It is too bold. The card would look better without it.

**Comment by nmoust** [comment]
Would something like that work?

![voc_excel_logo](https://github.com/user-attachments/assets/1ad4133a-7bb8-4d19-92ce-101a9446080c)

**Comment by dalito** [comment]
This is also too "heavy" (in comparison to the other design elements). I changed now to the pure screenshot and improved the text and layout of the cards.

I accidentally committed directly without a PR. The changes are deployed, so I am closing this issue.
